DEBUG = False

# Настройки логирования
LOG_LEVEL = 'INFO'  # Можно изменить на 'DEBUG' для подробного логирования

TELEGRAM_API_TOKEN = "8161286312:AAEJP6NfLW9koP7_EiOnBnsF3T6Ck3OPUF8"  # 7921991483:AAHM8c918j5B9rGKiegUsZCt1N89vtePJP4
SMS_TOKEN = 'c9afa2690ed58aeb83dec04833e0fe1c'

ADMIN_IDS = [8195693077]  # 6213103612 -              8195693077 (я)
DELIVERY_IDS = [993108283]  # 7843162799 -          993108283 (я)

ENTER_CONFIRMATION_CODE = 10

PHOTOS_DIR = "photos"
DATA_DIR = "data"
USERS_JSON = f"{DATA_DIR}/users.json"
REQUESTS_JSON = f"{DATA_DIR}/requests.json"

SERVICE_CENTERS_JSON = f"{DATA_DIR}/service_centers.json"
DELIVERY_TASKS_JSON = f"{DATA_DIR}/delivery_tasks.json"
PAYMENT_JSON = f"{DATA_DIR}/payment.json"
# Состояния для ConversationHandler
CREATE_REQUEST_LOCATION, ADMIN_PANEL, REGISTER, CREATE_REQUEST_DESC, CREATE_REQUEST_PHOTOS, ASSIGN_REQUEST, CREATE_DELIVERY_TASK, ENTER_NAME, ENTER_PHONE = range(9)

CREATE_REQUEST_CATEGORY = 11
CREATE_REQUEST_DATA = 12
CREATE_REQUEST_ADDRESS = 13
CREATE_REQUEST_CONFIRMATION = 14
CREATE_REQUEST_COMMENT = 'CREATE_REQUEST_COMMENT'


SC_MANAGEMENT_ADD_NAME = 21
SC_MANAGEMENT_ADD_ADDRESS = 22
SC_MANAGEMENT_ADD_PHONE = 23
SC_MANAGEMENT_DELETE = 24
SC_MANAGEMENT_LIST = 25
SC_ASSIGN_REQUESTS = 26

ENTER_REPAIR_PRICE = 27

CONFIRMATION = 28

# Статусы заявок
ORDER_STATUS_NEW = 'Новая'
ORDER_STATUS_ASSIGNED_TO_SC = 'Назначена в СЦ'
ORDER_STATUS_DELIVERY_TO_CLIENT = 'Доставщик в пути. К клиенту'
ORDER_STATUS_CLIENT_REJECTED = 'Клиент не подтвердил отправку'
ORDER_STATUS_DELIVERY_TO_SC = 'Доставщик в пути. К СЦ'
ORDER_STATUS_IN_SC = 'В СЦ'
ORDER_STATUS_READY = 'Готов к выдаче'
ORDER_STATUS_COMPLETED = 'Завершен'
ORDER_STATUS_WAITING_SC = 'Ожидает приёмки СЦ'

ORDER_STATUS_DELIVERY_TO_SC = 'Доставщик в пути. К СЦ'
ORDER_STATUS_DELIVERY_TO_CLIENT = 'Доставщик в пути. К клиенту'

ORDER_STATUS_SC_TO_CLIENT = "Доставка из СЦ клиенту"
ORDER_STATUS_PICKUP_FROM_SC = "Ожидает забор из СЦ"

ORDER_STATUS_REPAIR_COMPLETED = 'Ремонт завершен, ожидает доставки'

DELIVERY_MENU = 'DELIVERY_MENU'

ENTER_SC_CONFIRMATION_CODE = 30

# Состояния для оценки обслуживания
RATING_SERVICE = 100
FEEDBACK_TEXT = 101

# Состояния для просмотра чата
WAITING_REQUEST_ID = 'WAITING_REQUEST_ID'

# Состояния для оплаты
WAITING_PAYMENT = "WAITING_PAYMENT"
WAITING_PAYMENT_CONFIRM = "WAITING_PAYMENT_CONFIRM"
PAYMENT_API_URL = "https://dombyta.by/tgbrqst01.php"
WAITING_PAYMENT_CONF = "WAITING_PAYMENT_CONF"

WAITING_FINAL_PAYMENT = "WAITING_FINAL_PAYMENT"

WAITING_FOR_PRICE = "WAITING_FOR_PRICE"