TELEGRAM_API_TOKEN = "8161286312:AAEJP6NfLW9koP7_EiOnBnsF3T6Ck3OPUF8"  # 7921991483:AAHM8c918j5B9rGKiegUsZCt1N89vtePJP4
SMS_TOKEN = 'c9afa2690ed58aeb83dec04833e0fe1c'

ADMIN_IDS = [8195693077]  # 6213103612 - 8195693077 (я)
DELIVERY_IDS = [993108283]  # 7843162799 - 993108283 (я)
SC_IDS = []

ENTER_CONFIRMATION_CODE = 10

PHOTOS_DIR = "photos"
DATA_DIR = "data"
USERS_JSON = f"{DATA_DIR}/users.json"
REQUESTS_JSON = f"{DATA_DIR}/requests.json"

SERVICE_CENTERS_JSON = f"{DATA_DIR}/service_centers.json"
DELIVERY_TASKS_JSON = f"{DATA_DIR}/delivery_tasks.json"

# Состояния для ConversationHandler
CREATE_REQUEST_LOCATION, ADMIN_PANEL, REGISTER, CREATE_REQUEST_DESC, CREATE_REQUEST_PHOTOS, ASSIGN_REQUEST, CREATE_DELIVERY_TASK, ENTER_NAME, ENTER_PHONE = range(9)

CREATE_REQUEST_CATEGORY = 11
CREATE_REQUEST_DATA = 12
CREATE_REQUEST_ADDRESS = 13
CREATE_REQUEST_CONFIRMATION = 14

ORDER_STATUS_NEW = 'Новая'
ORDER_STATUS_ASSIGNED_TO_SC = 'Назначена в СЦ'
ORDER_STATUS_DELIVERY_TO_CLIENT = 'Доставщик в пути. К клиенту'
ORDER_STATUS_CLIENT_REJECTED = 'Клиент не подтвердил отправку'
ORDER_STATUS_DELIVERY_TO_SC = 'Доставщик в пути. К СЦ'
ORDER_STATUS_IN_SC = 'В СЦ'
ORDER_STATUS_READY = 'Готов к выдаче'
ORDER_STATUS_COMPLETED = 'Завершен'
ORDER_STATUS_WAITING_SC = 'Ожидает приёмки СЦ'

DELIVERY_MENU = 'DELIVERY_MENU'